version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "furo"
          - "genbadge"
          - "jsonschema"
          - "PyGithub"
          - "pyright"
          - "pytest-cov"
          - "pytest-regressions"
          - "pytest"
          - "PyYaml"
          - "sphinx_design"
          - "sphinx-autobuild"
          - "sphinx-syntax"
          - "sphinx-vhs"
          - "sphinx"
          - "sybil"
          - "toml"
          - "tox"
          - "typing_extensions"
          - "virtualenv-pyenv"
      style:
        patterns:
          - "cl-keeper"
          - "prek"
          - "ruff"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
