repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        entry: ruff check --force-exclude
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff format
        language: system
        entry: ruff format --force-exclude
        types_or: [python, pyi]
        require_serial: true
      - id: check-preamble
        name: check that python files start with license comment
        language: system
        entry: scripts/check_file_headers
        types: [python]
        files: 'yuio/.*'
        exclude: '^(yuio/_dist/.*|yuio/_version.py)'
      - id: clk
        name: changelog keeper
        language: system
        entry: clk pre-commit-check
        require_serial: true
        types_or: [toml, yaml, markdown]
      - id: clk-tags
        name: changelog keeper (check tags)
        language: system
        entry: clk pre-commit-check-tag
        always_run: true
        pass_filenames: false
        require_serial: true
        stages: [pre-push]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^test/regression_data/.*$"
      - id: end-of-file-fixer
        exclude: "^test/regression_data/.*$"
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
